###################################################
### RefineTemplateManager configuration example ###
###################################################
# An example YAML configuration to modify.
# Call `RefineTemplateManager.from_yaml(path)` to load this configuration.
template_volume_path: /some/path/to/template.mrc
micrograph_path:      /some/path/to/micrograph.mrc
particle_stack:
  df_path: /some/path/to/particles.csv  # Needs to be readable by pandas
  original_template_size: [512, 512]
  extracted_box_size: [528, 528]
preprocessing_filters:
  whitening_filter:
    do_power_spectrum: true
    enabled: true
    max_freq: 0.5  # In terms of Nyquist frequency
    num_freq_bins: null
  bandpass_filter:
    enabled: false
    falloff: null
    high_freq_cutoff: null
    low_freq_cutoff: null
computational_config:
  gpu_ids: 0
  num_cpus: 1